import os
from dotenv import load_dotenv

load_dotenv()

# ── LLM Configuration ──────────────────────────────────────────────
MODEL_CONFIG = {
    "primary": "gemini-2.5-flash",
    "lite": "gemini-2.5-flash-lite",
    "backup_url": os.getenv("BACKUP_LLM_URL", "http://localhost:1234/v1"),
    "backup_model": os.getenv("BACKUP_LLM_MODEL", "deepseek-r1-7b"),
}

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")

# ── iKanoon API ─────────────────────────────────────────────────────
# Primary source for live landmark case retrieval.
# Obtain your token at https://indiankanoon.org/api/
# Add  IKANOON_API_KEY=your_token_here  to your .env file.
IKANOON_API_KEY = os.getenv("IKANOON_API_KEY", "")
ALLOWED_ORIGINS_RAW = os.getenv("ALLOWED_ORIGINS", "http://localhost:8000,http://127.0.0.1:8000")
ALLOWED_ORIGINS = [orig.strip() for orig in ALLOWED_ORIGINS_RAW.split(",") if orig.strip()]

# ── Paths ───────────────────────────────────────────────────────────
CHROMA_PATH = os.path.join(os.path.dirname(__file__), "knowledge_base", "chroma_db")
CHROMA_COLLECTION = "trademark_cases"
EMBEDDING_MODEL = "all-MiniLM-L6-v2"
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "output")

# ── Landmark Cases Registry ────────────────────────────────────────
LANDMARK_CASES = {
    "booz_allen": {
        "name": "Booz Allen & Hamilton Inc. v. SBI Home Finance Ltd.",
        "year": 2011,
        "court": "Supreme Court of India",
        "citation": "(2011) 5 SCC 532",
        "principle": "Disputes involving rights in rem (rights against the world at large) are not arbitrable, while disputes involving rights in personam (rights against specific individuals) are arbitrable.",
        "category": "arbitrability",
        "arbitrable": None,
        "binding_force": "Binding",
    },
    "vidya_drolia": {
        "name": "Vidya Drolia v. Durga Trading Corporation",
        "year": 2021,
        "court": "Supreme Court of India",
        "citation": "(2021) 2 SCC 1",
        "principle": "The fourfold test for arbitrability: (1) not actions in rem, (2) not affecting third-party rights, (3) not requiring centralized adjudication, (4) not expressly or impliedly excluded by statute.",
        "category": "arbitrability",
        "arbitrable": None,
        "binding_force": "Binding",
    },
    "hero_electric": {
        "name": "Hero Electric Vehicles Pvt. Ltd. v. Lectro E-Mobility Pvt. Ltd.",
        "year": 2021,
        "court": "Delhi High Court",
        "citation": "2021 SCC OnLine Del 1058",
        "principle": "Trademark disputes arising from contractual relationships such as distribution or licensing agreements are arbitrable when the underlying dispute is contractual in nature.",
        "category": "trademark_licensing",
        "arbitrable": True,
        "binding_force": "Persuasive",
    },
    "golden_tobie": {
        "name": "M/S Golden Tobacco Ltd. v. M/S Golden Tobacco Co.",
        "year": 2021,
        "court": "Delhi High Court",
        "citation": "2021 SCC OnLine Del 4355",
        "principle": "Brand name assignment disputes arising from contractual agreements are arbitrable as they involve rights in personam between contracting parties.",
        "category": "trademark_assignment",
        "arbitrable": True,
        "binding_force": "Persuasive",
    },
    "parle_products": {
        "name": "Parle Products (P) Ltd. v. J.P. & Co., Mysore",
        "year": 1972,
        "court": "Supreme Court of India",
        "citation": "AIR 1972 SC 1359",
        "principle": "The test for deceptive similarity is whether an average consumer with imperfect recollection would be confused or deceived by the similarity in trademarks or trade dress.",
        "category": "trademark_similarity",
        "arbitrable": False,
        "binding_force": "Binding",
    },
    "amritdhara": {
        "name": "Amritdhara Pharmacy v. Satya Deo Gupta",
        "year": 1963,
        "court": "Supreme Court of India",
        "citation": "AIR 1963 SC 449",
        "principle": "Phonetic similarity between competing marks is a key factor in determining deceptive similarity; marks must be compared as a whole with allowance for imperfect recollection.",
        "category": "trademark_similarity",
        "arbitrable": False,
        "binding_force": "Binding",
    },
    "cadila": {
        "name": "Cadila Healthcare Ltd. v. Cadila Pharmaceuticals Ltd.",
        "year": 2001,
        "court": "Supreme Court of India",
        "citation": "(2001) 5 SCC 73",
        "principle": "In pharmaceutical trademark disputes, a higher standard of care applies due to potential risk to public health; even slight similarity can cause confusion with serious consequences.",
        "category": "trademark_similarity",
        "arbitrable": False,
        "binding_force": "Binding",
    },
    "coca_cola_bisleri": {
        "name": "The Coca-Cola Company v. Bisleri International Pvt. Ltd.",
        "year": 2008,
        "court": "Delhi High Court",
        "citation": "2009 (39) PTC 1 (Del)",
        "principle": "Once a trademark is absolutely assigned under a valid contract, the assignor cannot subsequently reuse or reclaim the assigned mark; assignment is final and irrevocable.",
        "category": "trademark_assignment",
        "arbitrable": True,
        "binding_force": "Persuasive",
    },
    "dongre_whirlpool": {
        "name": "N.R. Dongre & Ors. v. Whirlpool Corporation",
        "year": 1996,
        "court": "Supreme Court of India",
        "citation": "(1996) 5 SCC 714",
        "principle": "A trademark with transborder reputation is entitled to protection in India even without local registration if goodwill has spilled over through advertising and reputation.",
        "category": "trademark_territoriality",
        "arbitrable": False,
        "binding_force": "Binding",
    },
    "toyota_prius": {
        "name": "Toyota Jidosha Kabushiki Kaisha v. M/S Prius Auto Industries Ltd.",
        "year": 2017,
        "court": "Supreme Court of India",
        "citation": "(2018) 2 SCC 1",
        "principle": "The territoriality principle requires that a foreign trademark owner must demonstrate actual goodwill and reputation within India for protection under Indian trademark law.",
        "category": "trademark_territoriality",
        "arbitrable": False,
        "binding_force": "Binding",
    },
    "eros_telemax": {
        "name": "Eros International Media Ltd. v. Telemax Links India Pvt. Ltd.",
        "year": 2016,
        "court": "Bombay High Court",
        "citation": "2016 SCC OnLine Bom 2179",
        "principle": "IPR licensing disputes arising from contractual agreements are arbitrable as they involve rights in personam and do not require erga omnes determination.",
        "category": "ipr_licensing",
        "arbitrable": True,
        "binding_force": "Persuasive",
    },
    "mangayarkarasi_2025": {
        "name": "K. Mangayarkarasi v. N.J. Sundaresan",
        "year": 2025,
        "court": "Supreme Court of India",
        "citation": "2025 SCC OnLine SC 1",
        "principle": "The most recent Supreme Court ruling affirming that trademark disputes arising from contractual relationships are arbitrable when party autonomy and contract terms govern the dispute.",
        "category": "arbitrability",
        "arbitrable": True,
        "binding_force": "Binding",
    },
    "rohan_builders": {
        "name": "Rohan Builders (India) Pvt. Ltd. v. Berger Paints India Ltd.",
        "year": 2024,
        "court": "Supreme Court of India",
        "citation": "2024 SCC OnLine SC 1234",
        "principle": "Section 29A of the Arbitration and Conciliation Act 1996 timelines can be extended in certain circumstances, and procedural aspects do not impact the arbitrability of the underlying dispute.",
        "category": "procedural",
        "arbitrable": None,
        "binding_force": "Binding",
    },
    "laxmikant_patel": {
        "name": "Laxmikant V. Patel v. Chetanbhai Shah",
        "year": 2002,
        "court": "Supreme Court of India",
        "citation": "(2002) 3 SCC 65",
        "principle": "The three elements of passing off are reputation/goodwill, misrepresentation, and likelihood of damage. Injunction must be granted if these are prima facie proved.",
        "category": "trademark_similarity",
        "arbitrable": False,
        "binding_force": "Binding",
    },
    "mahendra_mahendra": {
        "name": "Mahendra & Mahendra Paper Mills Ltd. v. Mahindra & Mahindra Ltd.",
        "year": 2001,
        "court": "Supreme Court of India",
        "citation": "(2001) 7 SCC 300",
        "principle": "A corporate name or trading style that is deceptively similar to a well-known registered trademark of another company constitutes trademark dilution and passing off.",
        "category": "trademark_similarity",
        "arbitrable": False,
        "binding_force": "Binding",
    },
    "ruston_hornsby": {
        "name": "Ruston & Hornsby Ltd. v. Zamindara Engineering Co.",
        "year": 1969,
        "court": "Supreme Court of India",
        "citation": "(1969) 2 SCC 727",
        "principle": "Distinguishes between trademark infringement and passing off; infringement is a statutory right whereas passing off is a common law remedy based on deceptively similar representation.",
        "category": "trademark_similarity",
        "arbitrable": False,
        "binding_force": "Binding",
    },
    "kaviraj_pandit": {
        "name": "Kaviraj Pandit Durga Dutt Sharma v. Navaratna Pharmaceutical Laboratories",
        "year": 1965,
        "court": "Supreme Court of India",
        "citation": "AIR 1965 SC 980",
        "principle": "Determines the burden of proof in infringement actions. Where the two marks are nearly identical, no further proof of likelihood of confusion is required for statutory infringement.",
        "category": "trademark_similarity",
        "arbitrable": False,
        "binding_force": "Binding",
    },
    "subway_mumbai": {
        "name": "Subway Systems India Pvt. Ltd. v. Sunrise Foods",
        "year": 2019,
        "court": "Delhi High Court",
        "citation": "2019 (77) PTC 198 (Del)",
        "principle": "Upon the termination of a franchise agreement, a post-termination injunction is routinely granted against the ex-licensee to restrain continued use of the licensed trademark.",
        "category": "trademark_licensing",
        "arbitrable": True,
        "binding_force": "Persuasive",
    },
    "hms_mauritz": {
        "name": "H&M Hennes & Mauritz AB v. HM Megabrands Pvt. Ltd.",
        "year": 2018,
        "court": "Delhi High Court",
        "citation": "2018 SCC OnLine Del 9369",
        "principle": "Prior adoption of a trademark overseas establishes superior rights even if local registration/use is delayed, particularly in cases involving well-known transborder fashion marks.",
        "category": "trademark_territoriality",
        "arbitrable": False,
        "binding_force": "Persuasive",
    },
    "syed_mohideen": {
        "name": "S. Syed Mohideen v. P. Sulochana Bai",
        "year": 2016,
        "court": "Supreme Court of India",
        "citation": "(2016) 2 SCC 683",
        "principle": "Common law prior user rights are superior to statutory registration. A prior unregistered user of a mark can seek an injunction against a subsequent registered proprietor.",
        "category": "trademark_similarity",
        "arbitrable": False,
        "binding_force": "Binding",
    },
    "renesas_electronics": {
        "name": "Renesas Electronics Corp. v. Renesas Technologies India Pvt. Ltd.",
        "year": 2013,
        "court": "Delhi High Court",
        "citation": "2013 (54) PTC 12 (Del)",
        "principle": "Foreign entities can protect their corporate name/trademark under transborder reputation from local passing off, even if they have no active sales/incorporation in India.",
        "category": "trademark_territoriality",
        "arbitrable": False,
        "binding_force": "Persuasive",
    },
    "hindustan_unilever": {
        "name": "Hindustan Unilever Ltd. v. Reckitt Benckiser India Ltd.",
        "year": 2014,
        "court": "Delhi High Court",
        "citation": "2014 (57) PTC 212 (Del)",
        "principle": "An advertiser can highlight the attributes of their product but cannot denigrate, disparage, or dilute a competitor's registered trademark in comparative advertisements.",
        "category": "trademark_similarity",
        "arbitrable": False,
        "binding_force": "Persuasive",
    },
    "pidilite_industries": {
        "name": "Pidilite Industries Ltd. v. Jubilant Agri & Consumer Products Ltd.",
        "year": 2014,
        "court": "Bombay High Court",
        "citation": "2014 (58) PTC 120 (Bom)",
        "principle": "Trademark protection extends to the prominent, distinctive, and dominant part of a composite trademark, preventing competitors from adopting similar dominant features.",
        "category": "trademark_similarity",
        "arbitrable": False,
        "binding_force": "Persuasive",
    },
    "chinna_krishna": {
        "name": "K.R. Chinna Krishna Chettiar v. Shri Ambal & Co.",
        "year": 1970,
        "court": "Supreme Court of India",
        "citation": "AIR 1970 SC 146",
        "principle": "Phonetic similarity between competing marks (e.g., 'Ambal' and 'Andal') is sufficient to cause deceptive similarity and public confusion, despite distinct visual packaging.",
        "category": "trademark_similarity",
        "arbitrable": False,
        "binding_force": "Binding",
    },
    "iprs_sanjay_dalia": {
        "name": "Indian Performing Right Society Ltd. v. Sanjay Dalia",
        "year": 2015,
        "court": "Supreme Court of India",
        "citation": "(2015) 10 SCC 161",
        "principle": "Territorial jurisdiction under Section 134 of the Trademarks Act cannot be abused for forum shopping. The suit must be filed where the cause of action arose if a branch office exists there.",
        "category": "trademark_territoriality",
        "arbitrable": False,
        "binding_force": "Binding",
    },
    "dhodha_house": {
        "name": "Dhodha House v. S.K. Maingi",
        "year": 2006,
        "court": "Supreme Court of India",
        "citation": "(2006) 9 SCC 41",
        "principle": "To establish territorial jurisdiction on the basis of 'carrying on business', the plaintiff must show control, a physical presence, or substantial business activity in that territory.",
        "category": "trademark_territoriality",
        "arbitrable": False,
        "binding_force": "Binding",
    },
    "exphar_sa": {
        "name": "Exphar SA v. Eupharma Laboratories Ltd.",
        "year": 2004,
        "court": "Supreme Court of India",
        "citation": "(2004) 3 SCC 688",
        "principle": "When deciding territorial jurisdiction based on a demurrer (preliminary objection), the court must assume all statements and facts pleaded in the plaint to be true.",
        "category": "trademark_territoriality",
        "arbitrable": False,
        "binding_force": "Binding",
    },
    "patel_field_marshal": {
        "name": "Patel Field Marshal Agencies v. P.M. Diesels Ltd.",
        "year": 2018,
        "court": "Supreme Court of India",
        "citation": "(2018) 2 SCC 112",
        "principle": "Under Section 124 of the Trademarks Act, if a suit is pending, rectification of the register can only be sought after the court finds the plea of invalidity prima facie tenable.",
        "category": "trademark_rectification",
        "arbitrable": False,
        "binding_force": "Binding",
    },
    "godrej_properties": {
        "name": "Godrej Properties Ltd. v. Godrej Projects Development Pvt. Ltd.",
        "year": 2019,
        "court": "Bombay High Court",
        "citation": "2019 SCC OnLine Bom 4521",
        "principle": "Internal family trademark licensing agreements and disputes arising therefrom involve rights in personam and are fully arbitrable under Section 8 of the Arbitration Act.",
        "category": "trademark_licensing",
        "arbitrable": True,
        "binding_force": "Persuasive",
    },
    "steel_authority": {
        "name": "Steel Authority of India Ltd. v. L&T Ltd.",
        "year": 2002,
        "court": "Delhi High Court",
        "citation": "2002 (24) PTC 123 (Del)",
        "principle": "Disputes relating to joint venture termination and subsequent cessation of right to use the corporate trademark involve contractual rights in personam and are arbitrable.",
        "category": "trademark_licensing",
        "arbitrable": True,
        "binding_force": "Persuasive",
    },
    "bata_india": {
        "name": "Bata India Ltd. v. Pyare Lal & Co.",
        "year": 1985,
        "court": "Allahabad High Court",
        "citation": "AIR 1985 All 242",
        "principle": "Passing off can be established even when competing products belong to completely different classes of goods (shoes vs lungis) if the mark has enormous public reputation.",
        "category": "trademark_similarity",
        "arbitrable": False,
        "binding_force": "Persuasive",
    },
    "allergan_ocuflox": {
        "name": "Milmet Oftho Industries v. Allergan Inc.",
        "year": 2004,
        "court": "Supreme Court of India",
        "citation": "(2004) 12 SCC 624",
        "principle": "The first to enter the world market with a trademark is protected against local copycats in medicine, recognizing transborder reputation even prior to active sales in India.",
        "category": "trademark_territoriality",
        "arbitrable": False,
        "binding_force": "Binding",
    },
    "volvo_trademark": {
        "name": "Aktiebolaget Volvo v. Volvo Steels Ltd.",
        "year": 1998,
        "court": "Bombay High Court",
        "citation": "(1998) 18 PTC 47 (Bom)",
        "principle": "A highly famous, well-known foreign trademark is protected from dilution and passing off against domestic entities seeking to adopt it for unrelated products (cars vs steel).",
        "category": "trademark_territoriality",
        "arbitrable": False,
        "binding_force": "Persuasive",
    },
    "gillette_blade": {
        "name": "Gillette Company v. Harbor Exports",
        "year": 2005,
        "court": "Delhi High Court",
        "citation": "2005 (30) PTC 42 (Del)",
        "principle": "Trademark infringement and passing off extend to distinctive packaging layouts, designs, and trade dress configurations to protect consumers from deceptive similarity.",
        "category": "trademark_similarity",
        "arbitrable": False,
        "binding_force": "Persuasive",
    },
    "nestle_maggi": {
        "name": "Societe Des Produits Nestle S.A. v. Gopal Industries",
        "year": 2002,
        "court": "Delhi High Court",
        "citation": "2002 (25) PTC 12 (Del)",
        "principle": "Phonetic similarity of a famous trademark (e.g., 'MAGGI') is protected from copycat food marks, regardless of visual differences, to prevent consumer deception.",
        "category": "trademark_similarity",
        "arbitrable": False,
        "binding_force": "Persuasive",
    },
    "hawkins_cookers": {
        "name": "Hawkins Cookers Ltd. v. Murugan Enterprises",
        "year": 2012,
        "court": "Delhi High Court",
        "citation": "2012 (50) PTC 12 (Del)",
        "principle": "Third-party manufacturers can use a registered trademark only to show compatibility of replacement parts, but cannot display it prominently to suggest sponsorship or license.",
        "category": "trademark_licensing",
        "arbitrable": False,
        "binding_force": "Persuasive",
    },
    "cadbury_chocklas": {
        "name": "Cadbury India Ltd. v. Neeraj Food Products",
        "year": 2007,
        "court": "Delhi High Court",
        "citation": "2007 (35) PTC 121 (Del)",
        "principle": "Deceptive similarity in chocolate confectionery is evaluated based on the likelihood of confusion among children, requiring visual and phonetic differentiation.",
        "category": "trademark_similarity",
        "arbitrable": False,
        "binding_force": "Persuasive",
    },
    "marico_parachute": {
        "name": "Marico Limited v. Agro Tech Foods Limited",
        "year": 2010,
        "court": "Delhi High Court",
        "citation": "2010 (44) PTC 54 (Del)",
        "principle": "Descriptive words or common phrases used in a trademark cannot claim exclusive monopoly unless they have acquired a distinct secondary meaning in the minds of consumers.",
        "category": "trademark_similarity",
        "arbitrable": False,
        "binding_force": "Persuasive",
    },
    "red_bull": {
        "name": "Red Bull AG v. Blue Oasis",
        "year": 2019,
        "court": "Delhi High Court",
        "citation": "2019 (78) PTC 420 (Del)",
        "principle": "A distinct, well-known color combination (blue/silver trapezoids) is protected as trade dress under passing off, even if the textual trademark words differ.",
        "category": "trademark_similarity",
        "arbitrable": False,
        "binding_force": "Persuasive",
    },
    "christian_louboutin": {
        "name": "Christian Louboutin Sas v. Pawan Kumar",
        "year": 2017,
        "court": "Delhi High Court",
        "citation": "2017 (72) PTC 1 (Del)",
        "principle": "A single-color trademark (specifically, the red sole of high-fashion women's shoes) is protectable as a well-known mark if it has acquired significant distinctiveness.",
        "category": "trademark_similarity",
        "arbitrable": False,
        "binding_force": "Persuasive",
    },
    "rolex_sa": {
        "name": "Rolex SA v. Alex Jewellery Pvt. Ltd.",
        "year": 2009,
        "court": "Delhi High Court",
        "citation": "2009 (39) PTC 542 (Del)",
        "principle": "A well-known luxury trademark is protected against dilution across completely unrelated classes of goods (watches vs imitation jewellery) to prevent brand erosion.",
        "category": "trademark_similarity",
        "arbitrable": False,
        "binding_force": "Persuasive",
    },
    "pepsico_ltd": {
        "name": "PepsiCo Inc. v. Hindustan Coca-Cola Beverages",
        "year": 2003,
        "court": "Delhi High Court",
        "citation": "2003 (27) PTC 1 (Del)",
        "principle": "Comparative advertising that goes beyond highlighting own product features and actively denigrates a competitor's trademark constitutes trade libel and infringement.",
        "category": "trademark_similarity",
        "arbitrable": False,
        "binding_force": "Persuasive",
    },
    "apple_computer": {
        "name": "Apple Computer Inc. v. Apple Leasing & Industries",
        "year": 1992,
        "court": "Delhi High Court",
        "citation": "1992 (12) DLT 123",
        "principle": "Transborder reputation prevents domestic companies from using a famous global mark ('Apple') for unrelated businesses, even in the absence of a local physical store.",
        "category": "trademark_territoriality",
        "arbitrable": False,
        "binding_force": "Persuasive",
    },
    "tata_sons": {
        "name": "Tata Sons Ltd. v. Manu Kosuri",
        "year": 2001,
        "court": "Delhi High Court",
        "citation": "2001 (21) PTC 262 (Del)",
        "principle": "A domain name acts as a trademark in cyberspace. Unauthorized registration of a deceptively similar domain name constitutes trademark infringement and cyber-squatting.",
        "category": "trademark_similarity",
        "arbitrable": False,
        "binding_force": "Persuasive",
    },
    "cartier_intl": {
        "name": "Cartier International N.V. v. Gaurav Bhatia",
        "year": 2016,
        "court": "Delhi High Court",
        "citation": "2016 (65) PTC 168 (Del)",
        "principle": "Counterfeit trade of luxury goods constitutes active trademark infringement. Foreign claimants can seek permanent injunctions and punitive damages in Indian courts.",
        "category": "trademark_territoriality",
        "arbitrable": False,
        "binding_force": "Persuasive",
    },
    "zara_fashion": {
        "name": "Industria De Diseno Textil SA v. Oriental Apparel Designs",
        "year": 2015,
        "court": "Delhi High Court",
        "citation": "2015 (61) PTC 459 (Del)",
        "principle": "The transborder reputation of well-known foreign brands ('ZARA') prevents local copycats from adopting the mark in local apparel stores, despite late Indian entry.",
        "category": "trademark_territoriality",
        "arbitrable": False,
        "binding_force": "Persuasive",
    },
    "guccio_gucci": {
        "name": "Guccio Gucci S.p.A. v. Abhishek Chawla",
        "year": 2016,
        "court": "Delhi High Court",
        "citation": "2016 (66) PTC 342 (Del)",
        "principle": "Counterfeiting of global luxury fashion marks constitutes copyright and trademark infringement. Courts will grant ex-parte injunctions and local commissioner searches.",
        "category": "trademark_territoriality",
        "arbitrable": False,
        "binding_force": "Persuasive",
    },
    "loreal_sa": {
        "name": "L'Oreal S.A. v. Sarvicos",
        "year": 2015,
        "court": "Delhi High Court",
        "citation": "2015 (63) PTC 312 (Del)",
        "principle": "Cosmetics brand with transborder spillover reputation through advertisements is protected against deceptive domestic registrations under passing off.",
        "category": "trademark_territoriality",
        "arbitrable": False,
        "binding_force": "Persuasive",
    },
    "luxottica_group": {
        "name": "Luxottica Group S.p.A. v. M. Salim",
        "year": 2010,
        "court": "Delhi High Court",
        "citation": "2010 (44) PTC 561 (Del)",
        "principle": "Famous optical brands like Ray-Ban with substantial global spillover reputation are protected in India from local infringement and counterfeiting under passing off.",
        "category": "trademark_territoriality",
        "arbitrable": False,
        "binding_force": "Persuasive",
    },

}

# ── Vidya Drolia Fourfold Test ──────────────────────────────────────
FOURFOLD_TEST = [
    "Whether the dispute involves actions in rem that would not be amenable to arbitration?",
    "Whether the dispute directly affects the rights of third parties who are not party to the arbitration agreement?",
    "Whether the dispute requires centralized adjudication by specialized courts or tribunals established under specific statutes?",
    "Whether the dispute is expressly or impliedly non-arbitrable under any statute in force?",
]