const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, PageBreak, Header, Footer, PageNumber, LevelFormat, convertInchesToTwip } = require("docx");
const fs = require("fs");
const path = require("path");

const FONT = "Georgia";

function p(text, opts = {}) {
  return new Paragraph({
    spacing: { after: 200, line: 276 },
    alignment: opts.align || AlignmentType.JUSTIFIED,
    children: [new TextRun({ text, font: FONT, size: 22, italics: opts.italics || false, bold: opts.bold || false })],
  });
}

function heading(text, level = HeadingLevel.HEADING_1) {
  return new Paragraph({
    heading: level,
    spacing: { before: 320, after: 160 },
    children: [new TextRun({ text, font: FONT, bold: true })],
  });
}

function refPara(text) {
  return new Paragraph({
    spacing: { after: 140 },
    indent: { left: 360, hanging: 360 },
    children: [new TextRun({ text, font: FONT, size: 20 })],
  });
}

const titlePage = [
  new Paragraph({ spacing: { after: 60 }, alignment: AlignmentType.CENTER, children: [new TextRun({ text: "A Neuro-Symbolic Decision Support System for Arbitrability Determination in Indian Trademark Disputes", bold: true, size: 30, font: FONT })] }),
  new Paragraph({ spacing: { before: 200, after: 60 }, alignment: AlignmentType.CENTER, children: [new TextRun({ text: "[Author Name]¹, [Mentor Name]¹, [Faculty Reviewer Name]²", size: 22, font: FONT })] }),
  new Paragraph({ spacing: { after: 40 }, alignment: AlignmentType.CENTER, children: [new TextRun({ text: "¹Department of Computer Science, [Institution Name]", italics: true, size: 20, font: FONT })] }),
  new Paragraph({ spacing: { after: 300 }, alignment: AlignmentType.CENTER, children: [new TextRun({ text: "²[Law School / Faculty of Law], [Institution Name]", italics: true, size: 20, font: FONT })] }),
  new Paragraph({ spacing: { before: 200, after: 100 }, children: [new TextRun({ text: "Abstract", bold: true, size: 22, font: FONT })] }),
  p("Arbitral tribunals in India frequently confront a threshold question before any dispute reaches the merits: is this dispute arbitrable at all? Indian courts have developed a body of doctrine around this question, most notably through Booz Allen & Hamilton v. SBI Home Finance and Vidya Drolia v. Durga Trading Corporation, yet applying these tests correctly to a given fact pattern remains a matter of careful legal reasoning rather than mechanical lookup. Large language models are increasingly proposed as aids for exactly this kind of legal analysis, but recent empirical work has shown that retrieval-augmented generation, while an improvement over unaided generation, does not eliminate hallucination in legal outputs and can misstate the very statutory tests it is meant to apply. This paper presents a decision support system for trademark arbitration that addresses this concern architecturally rather than through prompting alone: a deterministic rule engine encodes the Booz Allen and Vidya Drolia tests directly, isolating the arbitrability determination from generative drift, while a tiered retrieval pipeline and a constrained large language model layer handle case retrieval and report drafting downstream of that decision. We describe the system's architecture, the statutory tests it operationalizes, and preliminary testing across seventeen fact patterns spanning license disputes, brand-similarity claims, and franchise terminations. We situate the system relative to recent neuro-symbolic legal AI and Indian legal NLP literature, identify a gap in the treatment of arbitrability as a distinct computational task from outcome prediction, and outline the evaluation work required to substantiate the system's reliability claims at scale."),
  new Paragraph({ spacing: { before: 100, after: 300 }, children: [new TextRun({ text: "Keywords: arbitrability, neuro-symbolic AI, legal decision support, retrieval-augmented generation, Indian arbitration law, trademark disputes, large language models", italics: true, size: 20, font: FONT })] }),
];

const body = [];

body.push(heading("1. Introduction"));
body.push(p("Section 34 of the Arbitration and Conciliation Act, 1996 permits an Indian court to set aside an arbitral award where the subject matter of the dispute was not capable of settlement by arbitration under the law in force. In practice, this means that an arbitrator who proceeds to decide a dispute that was never arbitrable in the first place risks producing an award with no legal effect, regardless of how sound the reasoning on the merits may be. Determining arbitrability is therefore not a formality; it is a jurisdictional gate that must be correctly navigated before the substantive dispute can be addressed at all."));
body.push(p("The test for arbitrability under Indian law has been shaped substantially by two Supreme Court decisions. Booz Allen & Hamilton Inc. v. SBI Home Finance Ltd. (2011) distinguished disputes that are actions in rem, generally non-arbitrable, from actions in personam, generally arbitrable, and identified categories of disputes conventionally reserved for courts or specialised tribunals. Vidya Drolia v. Durga Trading Corporation (2021) refined this into a four-fold test, asking whether a dispute involves rights in rem, affects third-party rights, requires centralised adjudication, or is expressly or impliedly non-arbitrable under a governing statute. Applying these tests to a trademark dispute requires distinguishing, for instance, between a pure infringement claim against a stranger to any contract, which is generally non-arbitrable because trademark registration and cancellation fall within the exclusive domain of specified statutory authorities, and a dispute arising from a licensing or distribution agreement containing an arbitration clause, which is generally arbitrable because it sounds in contract between parties who agreed to arbitrate."));
body.push(p("Large language models have been proposed with increasing frequency as tools for exactly this kind of legal issue-spotting and drafting task. Retrieval-augmented generation (RAG), in particular, is often presented as a solution to the hallucination problem that plagues unaided generative use in legal contexts, on the reasoning that grounding a model's output in retrieved statutory and case-law text should anchor its reasoning to authoritative sources. Empirical evaluation has complicated this picture considerably. Magesh et al. (2024) found that even leading commercial legal-AI products employing RAG hallucinated in a substantial minority of outputs, with a large share of those errors traceable not to the generative step but to failures earlier in the retrieval pipeline. Dahl et al. (2025) similarly concluded that RAG is, in their words, no panacea for legal hallucination. These findings matter directly for a system whose central output is a binary jurisdictional determination: an arbitrator who receives a hallucinated account of the Vidya Drolia test, however fluently written, is not well served by that output, and a system architecture that relies solely on prompting discipline to avoid this failure mode is relying on a mitigation that the literature suggests is unreliable."));
body.push(p("This paper describes a decision support system, referred to here as the Trademark Arbitration Decision Support System (Trademark DSS), that responds to this concern at the architectural level. The system separates the arbitrability determination itself, which is computed by a deterministic rule engine encoding the Booz Allen and Vidya Drolia tests directly against structured dispute facts, from the drafting of the surrounding legal report, which is produced by a large language model operating under an explicit statute-before-case-law constraint and grounded in case law retrieved through a tiered pipeline. The result is a system in which the single highest-stakes output, whether the tribunal has jurisdiction at all, is never generated by a language model, while the surrounding analytical narrative benefits from generative fluency and case-law grounding."));
body.push(p("The remainder of this paper is organised as follows. Section 2 situates the system relative to neuro-symbolic legal AI, legal RAG, and Indian legal NLP literature. Section 3 sets out the statutory tests the system operationalizes. Section 4 describes the system architecture. Section 5 discusses implementation. Section 6 reports preliminary testing across seventeen fact patterns. Section 7 discusses novelty, strengths, and limitations, and Section 8 concludes with the evaluation work required before the system's reliability claims can be made at scale."));

body.push(heading("2. Related Work"));
body.push(heading("2.1 Neuro-symbolic approaches to legal reasoning", HeadingLevel.HEADING_2));
body.push(p("The architectural pattern of separating symbolic decision logic from neural language generation has recently gained traction in legal AI as a response to the reliability limits of purely generative approaches. Wei et al. (2025) propose a neuro-symbolic framework for legal judgment prediction in which a large language model extracts fact elements from case narratives and represents them as variables for a symbolic rule system expressed in first-order logic, with a discrepancy loss used to align the two components during training. Colelough and Regli (2025) survey the broader neuro-symbolic AI in law literature and identify explainability of the derived symbolic logic as a persistent open problem, even as the underlying combination of learning and rule-based inference has matured. The system described in this paper follows the same general philosophy, using a language model where its fluency is an asset, namely drafting, and a deterministic rule layer where auditability and correctness are paramount, namely the jurisdictional determination itself. Where it departs from Wei et al. is in the task: existing neuro-symbolic legal work targets prediction of case outcomes on the merits, whereas the present system targets the antecedent question of whether a tribunal may hear the dispute at all, a task with a narrower and more explicitly codified statutory test but correspondingly higher consequences for error, given the possibility of an award being set aside under Section 34."));
body.push(heading("2.2 Retrieval-augmented generation in legal contexts", HeadingLevel.HEADING_2));
body.push(p("Lewis et al. (2020) introduced retrieval-augmented generation as a general technique for grounding generative output in retrieved documents, and the technique has since been widely adopted in legal applications on the premise that grounding reduces hallucination. Subsequent legal-domain evaluation has been considerably less optimistic than the general premise suggests. Magesh et al. (2024) benchmarked commercial legal-AI tools built on RAG and found hallucination rates that, while lower than unaided generation, remained non-trivial, with a substantial proportion of errors originating in retrieval failure rather than generation failure. Pipitone and Alami (2024) introduced LegalBench-RAG specifically to evaluate the retrieval component of legal RAG systems in isolation, reflecting a growing recognition that retrieval quality, not just generation quality, requires dedicated benchmarking. The present system's retrieval pipeline, structured as a tiered fallback across a live case-law API, a local vector store, and a curated static registry, is designed with this literature in mind, though the retrieval precision of the pipeline has not yet been benchmarked against a gold-standard case set, a gap addressed in Section 8."));
body.push(heading("2.3 Indian legal natural language processing", HeadingLevel.HEADING_2));
body.push(p("A distinct and increasingly active body of work addresses the specific challenges of applying NLP to Indian legal text, including multilingual statutory language and the structure of Indian case reporting. Malik et al. (2021) introduced the Indian Legal Documents Corpus (ILDC) for legal judgment prediction, and Joshi et al. (2024) extended this with IL-TUR, a multi-task benchmark spanning eight tasks across English and Indic languages. Domain-adapted language models such as InLegalBERT have been developed specifically for Indian legal text. Most directly relevant to the present system is recent work from BITS Pilani (Goel et al., 2025) proposing a domain-partitioned hybrid retrieval-augmented generation architecture for Indian legal research, integrating separate retrieval pipelines for case law, statutory text, and the Indian Penal Code behind a query router, and reporting a substantial improvement in an LLM-as-judge pass rate over a RAG-only baseline. That system addresses general-purpose Indian legal research query answering; the present system addresses a narrower, specific decision task, arbitrability determination, and incorporates an explicit symbolic decision layer rather than relying on retrieval and generation alone to arrive at a jurisdictional conclusion. The evaluation methodology of the BITS Pilani system, in particular its use of LLM-as-judge scoring, is a useful methodological reference for the evaluation work outlined in Section 8 of this paper."));
body.push(heading("2.4 AI in online dispute resolution", HeadingLevel.HEADING_2));
body.push(p("A separate strand of literature addresses artificial intelligence in online dispute resolution (ODR) more broadly, examining applications ranging from outcome-prediction tools to negotiation-support systems. Recent survey work situates AI-assisted adjudicator decision support as one of several emerging applications and calls for further attention to the design and policy dimensions of integrating such tools ethically into dispute-resolution workflows. Applied work in this space has also explored AI in combination with smart contracts and electronic-evidence authentication for arbitration proceedings, addressing evidentiary and procedural automation rather than the jurisdictional threshold question. Commercially, the American Arbitration Association has deployed production tooling for pre-filing risk assessment, again addressing likely outcome rather than arbitrability as such. The present system is best positioned within this literature as an application of AI decision support to a specific, previously unaddressed gatekeeping task within the ODR pipeline, rather than as a general-purpose research or outcome-prediction tool."));

body.push(heading("3. Legal Background: The Arbitrability Test"));
body.push(p("Two Supreme Court decisions anchor the system's rule engine. Booz Allen & Hamilton Inc. v. SBI Home Finance Ltd. (2011) 5 SCC 532 held that disputes classified as actions in rem, that is, disputes concerning a right exercisable against the world at large, are generally not arbitrable, and identified specific categories, including matters relating to the grant, revocation, and registration of intellectual property rights, as falling within the exclusive domain of designated statutory authorities. Vidya Drolia v. Durga Trading Corporation (2021) 2 SCC 1 restated and refined this position into a four-fold test, treating a dispute as non-arbitrable where it involves rights in rem, directly affects the rights of third parties who are not signatories to the arbitration agreement, requires centralised adjudication before a specialised court or tribunal established by statute, or is expressly or impliedly barred from arbitration by a governing statute. Applied to trademark disputes specifically, this produces a working distinction that the rule engine encodes directly: disputes concerning the registration, cancellation, or rectification of a trademark, or infringement claims against a party with no contractual privity to the claimant, are treated as generally non-arbitrable, since these implicate rights in rem and the exclusive jurisdiction of the Registrar of Trade Marks or specified courts under the Trade Marks Act, 1999. Disputes arising from a licensing, distribution, or franchise agreement containing a valid arbitration clause, by contrast, are treated as generally arbitrable, since these sound in contract between identified parties and do not, without more, implicate third-party rights or exclusive statutory jurisdiction."));

body.push(heading("4. System Architecture"));
body.push(heading("4.1 Overview", HeadingLevel.HEADING_2));
body.push(p("The system is organised as a pipeline of four stages operating over structured dispute intake: an arbitrability decision engine, a landmark case retrieval layer, a large language model drafting layer, and a report synthesis stage that assembles the outputs of the preceding stages into a structured Word document. The arbitrability decision, being the single output with direct legal consequence for the validity of any resulting award, is computed entirely outside the language model layer."));
body.push(heading("4.2 Arbitrability decision engine", HeadingLevel.HEADING_2));
body.push(p("Dispute intake captures the parties, the trademark in dispute, the nature of the dispute, whether a contract exists between the parties, whether the dispute affects third parties, and a free-text description of the underlying facts. The decision engine applies the Booz Allen and Vidya Drolia tests as two sequential rule sets over these structured fields, principally the categorical dispute-type field, matching against keyword sets associated with in-rem categories such as registration, cancellation, and rectification disputes, and with in-personam categories such as licensing and distribution disputes. The engine returns a binary arbitrability determination together with the specific statutory basis and case authority for that determination, which downstream stages are constrained to cite rather than to independently generate."));
body.push(heading("4.3 Landmark case retrieval", HeadingLevel.HEADING_2));
body.push(p("Case law retrieval proceeds through a tiered pipeline. A live query against the Indian Kanoon case-law API serves as the primary source, retrieving and ranking candidate judgments against the fact pattern. Where the API is unavailable or returns no usable results, retrieval falls back to a local vector store built over a curated corpus of Indian trademark and arbitration judgments, indexed using sentence-transformer embeddings. A third tier, a small curated registry of established landmark cases, serves as a final fallback ensuring the system always returns at least a minimal set of authoritative citations. This tiered design reflects the retrieval-failure concerns raised in the legal RAG literature discussed in Section 2.2, on the reasoning that a system with no usable case law to ground its drafting stage is more likely to produce ungrounded, and therefore potentially hallucinated, legal narrative."));
body.push(heading("4.4 Constrained drafting layer", HeadingLevel.HEADING_2));
body.push(p("Report narrative, including the framing of legal issues, the application of statutory provisions to the retrieved case law, and an adversarial analysis presenting arguments for and against the claimant's position, is produced by a large language model operating under an explicit prompt-level constraint requiring statutory text to be cited before case authority in every substantive section, a design choice referred to internally as the Law-First principle. Generation is attempted first against a primary hosted model, with automatic fallback to a secondary hosted model and, where both are unavailable, a locally hosted model, ensuring report generation is not fully dependent on any single external service. Each generation function retains a deterministic fallback template for the case where all three generation tiers fail, ensuring the system degrades to a clearly-flagged generic output rather than failing outright."));
body.push(heading("4.5 Report synthesis", HeadingLevel.HEADING_2));
body.push(p("The outputs of the preceding stages are assembled into a structured Word document comprising six sections: the arbitrability determination with its statutory basis, a landmark case analysis matrix mapping retrieved cases to the fact pattern, a set of issues for determination framed as questions, the applicable statutory provisions and their judicial interpretation, a proposed award framework, and the adversarial legal analysis. This structure mirrors the analytical sequence an arbitrator or counsel would themselves follow in assessing a dispute, and is intended to support rather than substitute for independent legal judgment, a distinction the system states explicitly in its output."));

body.push(heading("5. Implementation"));
body.push(p("The system is implemented as a FastAPI backend with a single-page frontend. The arbitrability engine and report generator are implemented in Python without external model dependencies, ensuring the jurisdictional determination itself has no external service dependency and no non-determinism. The retrieval layer uses ChromaDB as a role persistent vector store with all-MiniLM-L6-v2 sentence-transformer embeddings, alongside a live integration with the Indian Kanoon API as the primary retrieval source. The drafting layer uses Gemini 2.5 Flash as the primary language model, with Groq's Llama-3.3-70B-Versatile and a locally hosted DeepSeek-R1 model as successive fallbacks. Report assembly uses python-docx to produce the final structured document."));

body.push(heading("6. Preliminary Evaluation"));
body.push(p("At the time of writing, the system has been exercised against seventeen distinct fact patterns spanning license disputes, brand-similarity and passing-off claims, competing trademark registrations, franchise termination disputes, and disputes involving a foreign claimant, of which two have been formalised into a structured test harness with documented expected outcomes and the remainder exist as informal test runs. This testing has been sufficient to confirm the system produces syntactically and structurally complete reports across this range of fact patterns and to surface at least one specific limitation of the current rule engine, discussed in Section 7, namely that the arbitrability classification currently keys primarily off the categorical dispute-type field rather than the free-text dispute description, creating a potential blind spot where the two fields would suggest different classifications. We report this limitation explicitly rather than treating current testing as validating the rule engine's accuracy, because the testing to date has not included a labelled ground-truth dataset against which precision, recall, or any comparable metric could be computed. Section 8 sets out the evaluation design intended to close this gap, including a labelled evaluation set, an ablation comparing the rule-engine-based system against a large-language-model-only baseline with no symbolic layer, and retrieval-quality metrics for the case-law pipeline."));

body.push(heading("7. Discussion"));
body.push(heading("7.1 Novelty", HeadingLevel.HEADING_2));
body.push(p("The system's contribution, as situated against the literature in Section 2, is the application of a neuro-symbolic architecture, specifically the separation of a deterministic decision layer from a generative drafting layer, to the arbitrability determination task in Indian trademark law, a task that existing neuro-symbolic legal AI work has not addressed and that existing Indian legal RAG systems handle, where at all, through retrieval and generation alone rather than through an explicit symbolic decision component. The narrowness of this contribution is deliberate: arbitrability is a binary, statutorily codified threshold question with unusually well-defined tests, making it a tractable target for a symbolic decision layer in a way that broader legal reasoning tasks typically are not."));
body.push(heading("7.2 Strengths", HeadingLevel.HEADING_2));
body.push(p("The architecture directly addresses the retrieval-and-generation failure modes documented in the legal RAG literature by removing the highest-stakes decision from the generative pathway entirely, rather than relying on prompting discipline alone. The tiered retrieval and generation fallbacks provide operational resilience against the unavailability of any single external service, a practical concern for a tool intended for use in live arbitration workflows."));
body.push(heading("7.3 Limitations", HeadingLevel.HEADING_2));
body.push(p("Three limitations are acknowledged directly. First, the rule engine's current reliance on the categorical dispute-type field rather than the free-text description creates a classification blind spot on fact patterns where the two disagree, a limitation identified through internal code review rather than through the formal evaluation this paper argues is still required. Second, the landmark case registry underlying the tertiary retrieval fallback currently contains a small number of curated cases, sufficient for demonstration purposes but not yet validated as representative of the range of Indian trademark arbitrability jurisprudence. Third, and most significantly, the system has not yet been evaluated against a labelled dataset of sufficient size to report standard classification metrics, nor has it been compared against a large-language-model-only baseline, both of which are necessary before any claim of improved reliability over unconstrained generation can be substantiated empirically rather than architecturally."));

body.push(heading("8. Conclusion and Future Work"));
body.push(p("This paper has described a neuro-symbolic decision support system for arbitrability determination in Indian trademark disputes, situated the system relative to recent literature in neuro-symbolic legal AI, legal retrieval-augmented generation, and Indian legal NLP, and identified a specific gap the system addresses: the absence of prior work treating arbitrability determination, as distinct from outcome prediction, as a task suited to an explicit symbolic decision layer. The system's architecture is complete and has been exercised across a range of fact patterns, but its reliability claims currently rest on architectural reasoning rather than empirical evaluation. Future work required before publication of a full evaluation study includes construction of a labelled fact-pattern dataset of at least fifty to one hundred cases with arbitrability ground truth verified by a legal domain expert, an ablation study comparing the present architecture against a large-language-model-only baseline on that dataset, retrieval-precision benchmarking for the case-law pipeline against a gold-standard case set, and, where feasible, evaluation of report quality by practising arbitrators or intellectual property counsel. We intend this paper as a system description and a statement of the evaluation programme required to substantiate its central claim, rather than as a completed empirical validation of that claim."));

body.push(heading("Acknowledgments"));
body.push(p("The authors thank [Mentor Name] for facilitating engagement with the arbitration practitioner community and [Faculty Reviewer Name] for guidance on the Indian arbitrability doctrine underlying the system's rule engine."));

body.push(heading("References"));
const refs = [
  "Booz Allen & Hamilton Inc. v. SBI Home Finance Ltd., (2011) 5 SCC 532 (India).",
  "Colelough, B. C., & Regli, W. (2025). Neuro-symbolic AI in 2024: A systematic review. arXiv preprint.",
  "Dahl, M., Magesh, V., Suzgun, M., & Ho, D. E. (2025). Hallucinating law: Legal mistakes with large language models are pervasive. Journal of Empirical Legal Studies.",
  "Goel, A., Kumar, S., Agrawal, R., et al. (2025). A domain-partitioned hybrid retrieval-augmented generation and knowledge graph framework for Indian legal research. BITS Pilani preprint.",
  "Joshi, A., et al. (2024). IL-TUR: Benchmark for Indian legal text understanding and reasoning. Proceedings of ACL 2024.",
  "Lewis, P., Perez, E., Piktus, A., et al. (2020). Retrieval-augmented generation for knowledge-intensive NLP tasks. Advances in Neural Information Processing Systems, 33.",
  "Magesh, V., Surani, F., Dahl, M., Suzgun, M., Manning, C. D., & Ho, D. E. (2024). Hallucination-free? Assessing the reliability of leading AI legal research tools. Stanford RegLab preprint.",
  "Malik, V., Sanjay, R., Nigam, S. K., et al. (2021). ILDC for CJPE: Indian legal documents corpus for court judgment prediction and explanation. Proceedings of ACL-IJCNLP 2021.",
  "Pipitone, N., & Alami, G. H. (2024). LegalBench-RAG: A benchmark for retrieval-augmented generation in the legal domain. arXiv preprint.",
  "The Arbitration and Conciliation Act, 1996, No. 26, Acts of Parliament, 1996 (India).",
  "The Trade Marks Act, 1999, No. 47, Acts of Parliament, 1999 (India).",
  "Vidya Drolia v. Durga Trading Corporation, (2021) 2 SCC 1 (India).",
  "Wei, Z., Yu, C., Gan, L., et al. (2025). A neuro-symbolic framework for civil legal judgment prediction. Artificial Intelligence and Law.",
];
refs.forEach(r => body.push(refPara(r)));

const doc = new Document({
  sections: [
    {
      properties: {
        page: {
          size: { width: 12240, height: 15840 },
          margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 },
        },
      },
      headers: {
        default: new Header({ children: [new Paragraph({ alignment: AlignmentType.RIGHT, children: [new TextRun({ text: "Trademark DSS — Draft Manuscript", size: 16, font: FONT, italics: true })] })] }),
      },
      footers: {
        default: new Footer({
          children: [
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [new TextRun({ children: [PageNumber.CURRENT], size: 18, font: FONT })],
            }),
          ],
        }),
      },
      children: [...titlePage, ...body],
    },
  ],
});

const outputPath = "d:\\Projects\\trademark-arbitration-dss\\output\\Trademark_DSS_Paper_Draft_v1.docx";

Packer.toBuffer(doc).then((buf) => {
  fs.writeFileSync(outputPath, buf);
  console.log("done");
});
